name: task-management-app
on: [push]
jobs:
  task-management-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: github/super-linter@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          yarn-version: '1.22.15'
      - run: cd server
      - run: yarn install
      - run: yarn serve